services:
  - type: web
    name: conteo-mercaderia
    env: node
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    disk:
      name: cache
      mountPath: /var/cache/apt
      sizeGB: 1
